### ISSUE TITLE
nitdoc - Structured Documentation

### ISSUE THREAD

**Issue by Morriar** [nitlang/nit#1020]
# nitdoc - Structured Documentation
## TODO
- [ ] **Documentation as a User Manual**
  
  A user manual describes how to use the software through sections organized to improve the understanding of the API and its content. API elements can be presented in a logical order, based on use-cases and concerns instead of a fixed order linked to the structure of the code. Documentations from MSDN, PerlDoc or PHP.net are built as manuals.
  
  Features
  - [ ] Manual management of output structure
  - [ ] Generate / propose documentation structure
  - [ ] Incoherence detection
- [ ] **Reading Suggestions**
  
  Reading suggestions (or “see also”) provide further topics that can interest the reader based on a context. This context can be the current page or the task of the reader. A basic example would be to suggest reading the remove method to someone reading the documentation for add.
  
  Features
  - [ ] Manual management of cross references
  - [ ] Generate / propose internal and external references (also see for #305, #953, #991)
  - [ ] Incoherence detection
## Validation protocol

TODO
- [ ] Document quality measure for comprehension
- [ ] Internal / external linking quantification / qualification
- [ ] Topic analysis / extraction
- [ ] Indexing / Ranking measure from search engines
- [ ] Ease of maintenance
