### ISSUE TITLE
nitdoc - Examples in documentation

### ISSUE THREAD

**Issue by Morriar** [nitlang/nit#1024]
# nitdoc - Examples in documentation

When exploring a new software, developers need to use examples.

We define good examples as having the following characteristics:
- _minimal_: show only what is needed;
- _explanatory_: show a use case, a behavior or a good practice;
- _executable_: can be executed by the reader without modification or fix;
- _maintainable_: can be easily kept up-to-date with the source code and the documentation.
## TODO
- [ ] **Example reification**
  
  Provide a special directive to tag examples, Once tagged, examples can be formatted accordingly or grouped under special index pages.
  
  Features
  - [x] Tag examples (#683, #941)
  - [x] Hilight code
  - [ ] Hyper-link code
  - [ ] Format code
  - [ ] Insert examples at the right place (see #852)
  - [x] Group examples somewhere
- [ ] **Example checking**
  
  Examples need to be executed and automatically verified. Like code, testing examples is the only way to keep them up-to-date.
  
  Features
  - [x] Doc-Units
  - [ ] Check examples content (unused vars etc...)
  - [ ] Suggest reduction, check incoherence
- [ ] **Automatic Examples Generation**
  
  Examples can also be extracted from existing source code. Unit-tests contain hundreds to thousands of examples that meet our criterias. Source code of software clients is also a good
  source of examples.
  
  Features
  - [x] Extract from tests
  - [ ] Extract from clients
  - [ ] Generate & suggest
## Validation protocol

TODO
- [ ] Precision / recall for example extraction
- [ ] Code quality measures in generated / extracted examples
- [ ] Measure the helpfulness of the example considering a piece of documentation?
