### ISSUE TITLE
nitdoc - Easy access to information

### ISSUE THREAD

**Issue by Morriar** [nitlang/nit#1025]
# nitdoc - Easy access to information

One of the very first challenges for a developer who wants to use a new library is to find its documentation. When the documentation is accessible, the reader needs to find the information he is looking for within the documentation. Whether it be for searching text from documentation,
source code or examples, search engines provide a quick access to the information.
## TODO
- [ ] **Client-side search engine vs Server-side**
  
  Try both, choose one, use the other as fallback?
  
  Features
  - [x] Indexed name search
  - [ ] full-text search
  - [ ] code-search
  - [ ] example search
  - [x] indexing and ranking (#361)
  - [ ] search similar code
  - [ ] suggest answer to NL questions
## Validation protocol

TODO
- [ ] Precision / recall
