### ISSUE TITLE
nitdoc - No more stale documentation

### ISSUE THREAD

**Issue by Morriar** [nitlang/nit#1026]
# nitdoc - No more stale documentation

We group outdated, imprecise, incomplete and missing documentation under the stale documentation issue.
## TODO
- [ ] **Documentation Checking**
  
  Help to generate a good documentation.
  
  Features
  - [X] Provide warnings about missing documentation at generation
  - [ ] Provide _smart_ warnings about missing documentation at generation
  - [ ] Check spelling
  - [ ] Check links
  - [ ] Check references
  - [ ] Check comment concistency
  - [ ] Check that important members have examples
  - [ ] Check comment formatting according to a spec
- [ ] **Measuring Documentation Quality**
  
  Writers need to measure the quality of the documentation they produce.
  
  Features
  - [ ] GQM and other metrics
- [ ] **Collaborative Documentation**
  
  Once the documentation is generated, the reader can spot poorly documented areas of the library or errors. He then needs to send feedback to the writer to help improve the documentation.
  
  Features
  - [ ] Discussion
  - [x] Rating
  - [ ] Reintroduce Github plugin
  - [ ] Link with nitrpg?
  - [ ] Peer-review and gamification
## Validation protocol

TODO
- [ ] Empirical assessment over nit repository
