### ISSUE TITLE
todo list for string benches

### ISSUE THREAD

**Issue by privat** [nitlang/nit#1235]
* [ ] factorize things in the bash script
* [ ] draw lines instead of bars
* [ ] generate HTML document with png images
* [ ] setup one (or more) isolated headless machine that can run benches, maybe controlled with Jenkins. see with @Morriar there was some box used for tests with generics
