### ISSUE TITLE
doc_down: todo list

### ISSUE THREAD

**Issue by Morriar** [nitlang/nit#733]
Pre-processing:
- [x] autolink "http://"
- [ ] autolink model entities, namespaces, signature etc
- [ ] autolink pages and sections

Checking:
- [ ] spell checker
- [ ] style: indent, uppercase at the begining of the synopsys and a dot at the end...
- [ ] synopsys length
- [ ] ref checking: check reference like `foo` `Bar::foo`, also check visibility of the target
- [x] code checking: compile and try code examples.
- [ ] annotations: lowercase warning, annotation name...

Plus:
- [ ] warn on complex undocumented method: select some SE metrics that mark a method/class/module as "complex" and check if a documentation is associated
- [ ] suggest links: model or static analysis to find highly coupled method and propose a `SEE:` link
