### ISSUE TITLE
Todolist for new constructors

### ISSUE THREAD

**Issue by privat** [nitlang/nit#785]
- [x] introduce minimal new constructors #679
- [x] named constructors are normal methods (no more shenaningans) #783
- [x] annotation to change the order of the initialisers. #1158
- [x] can use methods as initialisers #787
- [ ] how to handle visibility?
- [ ] how to handle simple constructor by default?
  - annotation `default_init` on named constructor?
- [ ] write documentation (for the manual/spec)
