### ISSUE TITLE
nitdoc: foreign languages integration

### ISSUE THREAD

**Issue by Morriar** [nitlang/nit#788]
# Primary objective

Study the viability of a Nit centered tool (nitdoc) able to generate documentation for APIs in foreign OO languages.

Main targets are rnaked by popularity (according to the [Tiobe Index](http://www.tiobe.com/index.php/content/paperinfo/tpci/index.html)): Java, Objective-C, C++, C#, PHP, Python, JS, Ruby.
# TODO List

Prototyping:
- [ ] Collect models from other languages without writing/maintaining a parser for each.
- [ ] Check and fix limitations in the nit model, neo4j dbb, neo connector, nitdoc generator
- [ ] Chose the best way to interface nitdoc and other languages

Language integration:
- [ ] Java
- [ ] Objective-C
- [ ] C++
- [ ] C#
- [ ] PHP
- [ ] Python
- [ ] JS
- [ ] Ruby

Final tool:
- [ ] Store models in base (for each language)
- [ ] Store comments (possibly from external files) and source code in base when available
- [ ] Extract models (or parts of) from base
- [ ] Generate nitdoc for a language/project
- [ ] Collect models from GitHub
- [ ] Interface with nitx
