### ISSUE TITLE
jwrapper todo list

### ISSUE THREAD

**Issue by xymus** [nitlang/nit#794]
- [ ] Generate static methods on top-level
- [x] Extend primitive array support
- [ ] Enhance static overload support (currently, it suffixes the method name with a number)
- [ ] Support fields by adding different getter/setters
- [x] Reword Java method name to Nit style (ex: replace `set_foo` with `foo=`)

@Freddrickk

**Comment by xymus** [comment]
- [ ] Execute on a .jar file or many .class files
- [ ] Better naming for method attributes by using their type

@MehdiAit

**Comment by privat** [comment]
ping @xymus to update the checkboxes
