### ISSUE TITLE
neo_doxygen: todo list and known issues

### ISSUE THREAD

**Issue by jcbrinfo** [nitlang/nit#837]
As requested by @Morriar.
# Projet d’importation de la sortie XML de doxygen vers un graphe lu par `neo.nit`

Référence pour le format de Doxygen: https://github.com/doxygen/doxygen/blob/master/templates/xml/compound.xsd
## Progression de l’outil
- [X] Lister les classes.
  - [X] Inclure les relations d’héritage.
  - [ ] Inclure la généricité (moins prioritaire).
- [X] Lister les espaces de noms.
- [X] Lister les fichiers.
- [x] Lister les membres.
  - [ ] Inclure la généricité (moins prioritaire).
- [X] Importer les listes de paramètres.
- [X] Supporter Python.
- [ ] Mettre en forme la documentation (moins prioritaire).
## Glossaire
- Composite (« compound ») : Un répertoire, un fichier ou toute structure
  habituellement à la racine d’un fichier. Correspond à un fichier XML dans
  doxygen.
- Genre (« kind ») : Étiquette utilisée pour préciser le méta-type.
- Membre (« member ») : Structure entièrement incluse dans un composite et
  qui n’est pas un composite.
### Non-géré par le modèle Nit
- [ ] Général
  - [X] Visibilité « package »
  - [ ] Virtualité
    - [ ] `non-virtual`
    - [ ] `virtual`
    - [ ] `pure-virtual`
  - [X] Absence de projet
    - Tous les groupes à la racine sont lié à un même groupe (portant le
      nom du projet) et à un même projet.
    - Le nom du projet est spécifié par l’utilisateur.
  - [ ] Tableaux
  - [x] Type constitué d’un nombre indéterminé d’identifiants et de mots-clés
- [ ] Composite
  - [ ] `title`
  - [ ] Genre
    - [ ] `struct`
    - [ ] `union`
    - [ ] `protocol`
    - [ ] `category`
    - [ ] `exception`
    - [ ] `singleton`
    - [ ] `type`
    - [X] `file`
      - Générer un module pour chaque espace de nom utilisé par le fichier.
      - Le nom des modules a la forme suivante : `nom_projet::espace_de_nom::nom_fichier`.
    - [X] `namespace` : Utiliser un `MGroup`.
    - [ ] `group`
    - [ ] `page`
    - [ ] `example`
    - Solutions possibles
      - Ajouter des nouveaux genres.
      - Ajouter un genre style libre (valeur non restreinte).
        - Permetterait de gérer aussi les attributs booléens.
  - [ ] Les attributs booléens `abstract`, `final` et `sealed`
    - Solution possible : mettre dans `kind` (ce qui est fait pour le moment).
      - Si `kind` est une énumération, il y a trop de possibilités à considérer.
  - [ ] Visibilité et virtualité de l’héritage
    - Ignoré pour l’instant.
  - [ ] Classes de base à l’extérieur du projet
  - [X] Classes imbriqués
  - [ ] Sections au niveau d’un composite
    - [ ] En-tête
    - [ ] Description
    - [ ] Genre
    - Pour l’instant, l’outil ignore ce niveau et passe directement
      aux membres.
    - Il est possible que les sections n’aient aucune valeur ajoutée.
      En fait, ça semble correspondre aux sections que Doxygen génère pour
      les autres sorties (membres publiques, membres privés, etc.).
- [ ] Membres
  - [ ] Genre
    - [ ] `define`
    - [ ] `event`
    - [ ] `typedef`
    - [ ] `enum`
    - [ ] `signal`
    - [ ] `property`
      - Semble être utilisé pour les propriétés à la Microsoft, c’est-à-dire des triplets `let`-`set`-`get`.
    - [ ] `prototype`
    - [ ] `friend`
    - [ ] `dcop`
    - [ ] `slot`
    - [ ] `service`
  - [ ] Virtualité
  - [ ] Redéfinition de la visibilité
  - [ ] Attributs booléens d’un membre
  - [ ] Attribut `accessor` dans le cas d’un « Objective-C 2.0 property accessor »
  - [ ] Paramètres de « template »
  - [ ] Exceptions levées
  - [ ] Redéfinition de plusieurs membres
    - Doxygen définit la multiplicité de la relation de réimplémentation
      (équivalent des « redef ») comme étant de 0 à plusieurs dans les
      deux sens, ce qui cause un problème pour la relation `DEFINES`
      (plusieurs vers un).
      - Pour l’instant, je prends la première racine trouvée selon un 
        parcours en largeur.
  - [ ] Plusieurs membres du même nom (surcharge).
  - [x] Membres faisant partie d’un composite qui n’est pas une classe
    (exemple: directement dans un espace de nom).
- [ ] Paramètre
  - [ ] Valeur par défaut
### Non-géré par Nitdoc
- [ ] Titre au niveau d’un composite : Ignoré pour l’instant.
- [ ] Emplacements
  - [ ] Sans fichier
  - [ ] Sans coordonnées
- [ ] Absence de dépendance explicite entre les modules (exemple: Java)
  - Pour l’instant, Nitdoc utilise l’héritage des classes dans le module pour
    générer un diagramme, mais ne met aucun lien hypertexte. Aussi, ça donne
    une vision très limitée du vrai graphe de dépendances.
  - Solution à investiguer : Extraire l’information à partir des diagrammes
    inclus dans les définitions de composites.
- [ ] Documentation d’un paramètre
### Proplèmes spécifiques à `neo.nit`
- [ ] La propriété `location` n’est pas réflexive (le chargeur n’accepte pas
  tous les formats de `Location::to_s`).
### Concepts de Doxygen que je ne comprend pas encore complètement
- [ ] Distinctions entre `briefdescription`, `detaileddescription` et
  `inbodydescription`
  - Pour l’instant, seul `detaileddescription` est supporté (cas javadoc).
- [ ] `title` d’un composite.
- [ ] `ambiguityscope`
- [ ] Les diagrammes (par manque de temps)
  - [ ] Pourrait servir à récupérer les dépendances implicites (à vérifier).
- [x] Le typage (`LinkedTextType`)
  - Un texte avec zéro, un ou plusieurs liens.
- [ ] L’élément `read`
- [ ] L’élément `write`
- [ ] L’élément `bitfield`
- [ ] L’attribut `array` : À quoi la valeur correspond-t-elle?
### Ce que Doxygen ne génère pas (ou qui nécessite une configuration)
- [ ] Documentation des espaces de noms
  - Problème possiblement spécifique au vieux code Java, où la documentation
    n’est pas dans un `*.java`.
  - Je n’ai pas trouvé d’option pour que Doxygen prenne en compte les `package.html`.
- [ ] Chemin d’accès relatifs
  - Doxygen semble toujours mettre les chemins absolus pour la sortie XML,
    peu importe la configuration.
- [ ] Équivalent des attributs `is_init`, `is_intern` et `is_extern` pour les méthodes.
  - Est-ce réellement nécessaire pour Nitdoc?
- [ ] Les liens de redéfinitions sont pas toujours indiqués (pourquoi?).
- [ ] Java: Certains mot-clés ne sont pas interprétés.
  - [X] `abstract`
  - [X] `...`
### Solutions générales proposés
- Pour le manque de flexibilité du modèle.
  - (IMPOSSIBLE) Utiliser des annotations.
    - Les annotations n’interviennent pas au niveau du modèle.
  - (POSSIBLE) Ajouter un dictionnaire de propriétés étendues
    (sans restrictions) à `MEntity`.
    - Permet d’apporter rapidement des modifications relatives aux propriétés
      reconnues.
  - (POSSIBLE) Raffiner les classes du modèle pour ajouter les propriétés dont
    on a besoin.
